import { auth } from "../lib/auth";

/**
 * Verify Email Endpoint
 * 
 * Processes email verification token generated by Better-Auth.
 * When a user clicks verification link in their email, Better-Auth
 * generates a link like: /verify-email?token=...
 * 
 * This endpoint calls Better-Auth handler which:
 * 1. Validates the token
 * 2. Updates user's emailVerified status in database
 * 3. Redirects user to login page
 */
export default defineEventHandler(async (event) => {
  console.log('[Verify-Email] Processing email verification request')
  console.log('[Verify-Email] Query params:', getQuery(event))
  
  // Better-Auth will handle verification through its handler
  // The handler will:
  // - Validate the token
  // - Update emailVerified status in database
  // - Handle redirect to callbackURL (default: /auth/login)
  const response = await auth.handler(toWebRequest(event))
  
  console.log('[Verify-Email] Better-Auth response processed')
  
  return response
})